name: t2i-ddm-amd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchvision
    - torch-directml
    - diffusers
    - transformers
    - accelerate
    - datasets
    - webdataset
    - img2dataset
    - wandb
    - einops
    - timm 