name: t2i-ddm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchvision
    - --index-url https://download.pytorch.org/whl/cu121
    - diffusers
    - transformers
    - accelerate
    - datasets
    - webdataset
    - img2dataset
    - wandb
    - einops
    - timm
    - xformers
    - flash-attn 